# Generated by Django 4.2.26 on 2025-11-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('surgeries', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medical_records'),
        ),
    ]
