from pymongo import MongoClient, ASCENDING, DESCENDING
from django.conf import settings
from datetime import datetime
import bcrypt
from bson import ObjectId
from pymongo import GEOSPHERE

from .utils import normalize_mongo_doc

client = MongoClient(getattr(settings, 'MONGO_URI', 'mongodb://localhost:27017/'))
db = client['dawini_db']

# All collections
collections = {
    'users': db['users'],
    'patients': db['patients'],
    'doctors': db['doctors'],
    'vitals_records': db['vitals_records'],
    'medical_records': db['medical_records'],
    'alerts': db['alerts'],
    'appointments': db['appointments'],
    'prescriptions': db['prescriptions'],
    'lab_results': db['lab_results'],
    'medical_files': db['medical_files'],
    'chat_histories': db['chat_histories'],
    'chat_sessions': db['chat_sessions'],
    'chat_messages': db['chat_messages'],
    'subscriptions': db['subscriptions'],
    'payments': db['payments'],
    'notifications': db['notifications'],
    'feedbacks': db['feedbacks'],
    'support_tickets': db['support_tickets'],
    'health_goals': db['health_goals'],
    'symptoms': db['symptoms'],
    'sleep_logs': db['sleep_logs'],
    'exercise_logs': db['exercise_logs'],
    'nutrition_logs': db['nutrition_logs'],
    'medication_reminders': db['medication_reminders'],
    'lab_orders': db['lab_orders'],
    'medical_documents': db['medical_documents'],
    'document_reviews': db['document_reviews'],
    'clinics': db['clinics'],
    'plans': db['plans'],
    
'clinic_staff': db['clinic_staff'],           # users who work at a clinic
    'clinic_doctors': db['clinic_doctors'],         # link doctor ↔ clinic
    'clinic_themes': db['clinic_themes'],          # logo, primary color, name, etc.
    'clinic_requests': db['clinic_requests'],        # patient requests to a specific clinic
    'clinic_invoices': db['clinic_invoices'],        # invoices generated by clinic staff
    'clinic_reviews': db['clinic_reviews']          # ratings & comments → used for recommendation
}

def ensure_mongo_setup():
    """Create collections and indexes if not exist (called on startup)."""
    try:
        collections['clinics'].create_index([("location", GEOSPHERE)], name="location_2dsphere")

        collections['clinics'].create_index([("rating", DESCENDING)])
        collections['clinics'].create_index("is_active")
        collections['clinic_staff'].create_index([("clinic_id", 1), ("user_username", 1)], unique=True)
        collections['clinic_invoices'].create_index("invoice_number", unique=True)
        collections['clinic_invoices'].create_index("patient_username")
        collections['clinic_invoices'].create_index("clinic_id")
        # Dans mongo_models.py ou directement dans la vue
        collections['medical_documents'].create_index("patient_username")
        collections['medical_documents'].create_index("doctor_username")
        collections['lab_orders'].create_index([("doctor_username", 1), ("patient_username", 1)])
        collections['users'].create_index("username", unique=True)
        collections['users'].create_index("email", unique=True)
        collections['alerts'].create_index("patient_username")
        collections['alerts'].create_index("created_at")
        collections['vitals_records'].create_index("patient_username")
        collections['vitals_records'].create_index("recorded_at")
        collections['vitals_records'].create_index([("patient_username", ASCENDING), ("recorded_at", DESCENDING)])
        collections['chat_histories'].create_index("session_id", unique=True)
        collections['chat_histories'].create_index("updated_at")
        collections['appointments'].create_index("patient_username")
        # Add more indexes as needed for other collections
        print("MongoDB collections and indexes ensured.")
    except Exception as e:
        print(f"Error ensuring Mongo setup: {e}")

# api/utils.py

from bson import ObjectId
from rest_framework.renderers import JSONRenderer
import json

class JSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        return super().default(o)

# Remplace le renderer par défaut de DRF
from rest_framework.renderers import JSONRenderer as BaseJSONRenderer

class JSONRenderer(BaseJSONRenderer):
    encoder_class = JSONEncoder






# ====================== USER MANAGEMENT ======================
class MongoUser:
    col = collections['users']

    @staticmethod
    def create_user(data):
        """
        Crée un utilisateur (patient ou docteur) avec tous les champs du formulaire
        """
        username = data['username'].strip().lower()
        email = data['email'].strip().lower()
        password = data['password']
        role = data.get('role', 'patient').lower()

        # Vérification doublon
        if MongoUser.col.find_one({"$or": [{"username": username}, {"email": email}]}):
            raise ValueError("Username ou email déjà utilisé")

        # Hash du mot de passe
        hashed = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

        # Champs communs
        user_doc = {
            "username": username,
            "email": email,
            "password_hash": hashed,
            "role": role,
            "first_name": data.get('first_name', '').strip(),
            "last_name": data.get('last_name', '').strip(),
            "phone": data.get('phone', ''),
            "birth_date": data.get('birth_date'),  # string ou date ISO
            "address": data.get('address', '').strip(),
            "created_at": datetime.utcnow(),
            "updated_at": datetime.utcnow(),
        }

        # Champs spécifiques aux docteurs
        if role == "doctor":
            user_doc.update({
                "bio": data.get('bio', "Médecin généraliste passionné par la santé connectée.").strip(),
                "specialty": data.get('specialty', "Médecine générale"),
                "rating": float(data.get('rating', 4.5)),
                "location": data.get('location', "Cabinet non précisé"),
                "years_experience": int(data.get('years_experience', 5)),
                "avatar_url": data.get('avatar_url', ''),
                "is_verified": False,
                "consultation_price": float(data.get('consultation_price', 250)),
            })

        result = MongoUser.col.insert_one(user_doc)
        user_doc['_id'] = str(result.inserted_id)
        user_doc.pop('password_hash', None)
        return user_doc

    @staticmethod
    def find_by_username(username):
        doc = MongoUser.col.find_one({"username": username.lower() if username else username})
        return doc

    @staticmethod
    def authenticate(username, password):
        user = MongoUser.find_by_username(username)
        if user and bcrypt.checkpw(password.encode('utf-8'), user['password_hash']):
            user.pop('password_hash', None)
            return user
        return None



# Relation helpers (e.g., get patient records)
def get_patient_vitals(patient_username):
    return list(collections['vitals_records'].find({"patient_username": patient_username}))


def get_patient_alerts(patient_username):
    return list(collections['alerts'].find({"patient_username": patient_username}))
def get_patient_appointments(patient_username):
    return list(collections['appointments'].find({"patient_username": patient_username}))
def get_patient_medical_records(patient_username):
    return list(collections['medical_records'].find({"patient_username": patient_username}))
# Add more relation helpers as needed
def get_doctor_patients(doctor_username):
    return list(collections['patients'].find({"assigned_doctor": doctor_username}))
def get_patient_prescriptions(patient_username):
    return list(collections['prescriptions'].find({"patient_username": patient_username}))
def get_patient_lab_results(patient_username):
    return list(collections['lab_results'].find({"patient_username": patient_username}))
def get_patient_medical_files(patient_username):
    return list(collections['medical_files'].find({"patient_username": patient_username}))
def get_patient_chat_histories(patient_username):
    return list(collections['chat_histories'].find({"patient_username": patient_username}))
def get_patient_subscriptions(patient_username):
    return list(collections['subscriptions'].find({"patient_username": patient_username}))
def get_patient_payments(patient_username):
    return list(collections['payments'].find({"patient_username": patient_username}))
def get_patient_notifications(patient_username):
    return list(collections['notifications'].find({"patient_username": patient_username}))
def get_patient_feedbacks(patient_username):
    return list(collections['feedbacks'].find({"patient_username": patient_username}))
def get_patient_support_tickets(patient_username):
    return list(collections['support_tickets'].find({"patient_username": patient_username}))
def get_patient_health_goals(patient_username):
    return list(collections['health_goals'].find({"patient_username": patient_username}))
def get_patient_symptoms(patient_username):
    return list(collections['symptoms'].find({"patient_username": patient_username}))
def get_patient_sleep_logs(patient_username):
    return list(collections['sleep_logs'].find({"patient_username": patient_username}))
def get_patient_exercise_logs(patient_username):
    return list(collections['exercise_logs'].find({"patient_username": patient_username}))
def get_patient_nutrition_logs(patient_username):
    return list(collections['nutrition_logs'].find({"patient_username": patient_username}))
def get_patient_medication_reminders(patient_username):
    return list(collections['medication_reminders'].find({"patient_username": patient_username}))
def get_patient_lab_orders(patient_username):
    return list(collections['lab_orders'].find({"patient_username": patient_username}))
def get_doctor_appointments(doctor_username):
    return list(collections['appointments'].find({"doctor_username": doctor_username}))
def get_doctor_medical_documents(doctor_username):
    return list(collections['medical_documents'].find({"doctor_username": doctor_username}))
def get_doctor_clinic_staff(doctor_username):
    return list(collections['clinic_staff'].find({"user_username": doctor_username}))
def get_doctor_clinic_doctors(doctor_username):
    return list(collections['clinic_doctors'].find({"doctor_username": doctor_username}))
def get_doctor_clinic_requests(doctor_username):
    return list(collections['clinic_requests'].find({"doctor_username": doctor_username}))
def get_plans():
    return list(collections['plans'].find({}))

    
class MongoDoctor:
    col = collections['doctors']

    @staticmethod
    def find_by_username(username):
        doc = MongoDoctor.col.find_one({"username": username.lower() if username else username})
        return doc
class MongoPatient:
    col = collections['patients']

    @staticmethod
    def find_by_username(username):
        doc = MongoPatient.col.find_one({"username": username.lower() if username else username})
        return doc
class MongoVitalsRecord:
    col = collections['vitals_records']

    @staticmethod
    def create_record(data):
        record_doc = {
            "patient_username": data['patient_username'],
            "systolic": data['systolic'],
            "diastolic": data['diastolic'],
            "glucose": data['glucose'],
            "heart_rate": data['heart_rate'],
            "spo2": data.get('spo2'),
            "temperature": data.get('temperature'),
            "recorded_at": data.get('recorded_at', datetime.utcnow()),
            "created_at": datetime.utcnow(),
        }
        result = MongoVitalsRecord.col.insert_one(record_doc)
        record_doc['_id'] = str(result.inserted_id)
        return record_doc
class MongoAlert:
    col = collections['alerts']

    @staticmethod
    def create_alert(data):
        alert_doc = {
            "patient_username": data['patient_username'],
            "alert_type": data['alert_type'],
            "message": data['message'],
            "is_acknowledged": False,
            "created_at": datetime.utcnow(),
        }
        result = MongoAlert.col.insert_one(alert_doc)
        alert_doc['_id'] = str(result.inserted_id)
        return alert_doc
from bson import ObjectId
from rest_framework.renderers import JSONRenderer
import json

class JSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        return super().default(o)

# Remplace le renderer par défaut de DRF
from rest_framework.renderers import JSONRenderer as BaseJSONRenderer

class JSONRenderer(BaseJSONRenderer):
    encoder_class = JSONEncoder
# api/utils.py
def clean_mongo_doc(doc):
    if doc and "_id" in doc:
        doc["_id"] = str(doc["_id"])
    return doc
class MongoClinic:
    col = collections['clinics']

    @staticmethod
    def create(data):
        result = MongoClinic.col.insert_one({
            **data,
            "rating": 0.0,
            "review_count": 0,
            "is_active": True,
            "created_at": datetime.utcnow(),
            "location": {"type": "Point", "coordinates": [data['longitude'], data['latitude']]}
        })
        return str(result.inserted_id)

    @staticmethod
    def get_nearby(lat, lng, max_distance=20000):  # 20km
        return list(MongoClinic.col.find({
            "location": {
                "$near": {
                    "$geometry": {"type": "Point", "coordinates": [lng, lat]},
                    "$maxDistance": max_distance
                }
            },
            "is_active": True
        }).sort("rating", -1).limit(20))

    @staticmethod
    def get_by_id(clinic_id):
        doc = MongoClinic.col.find_one({"_id": ObjectId(clinic_id)})
        return normalize_mongo_doc(doc) if doc else None

    @staticmethod
    def get_top_rated(limit=10):
        return list(MongoClinic.col.find({"is_active": True})
                    .sort("rating", -1).limit(limit))
